language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - CRATE=libs/bart_derive
  - CRATE=.
script:
  - cd "$CRATE"
  - cargo build --verbose
  - cargo test --verbose
