[package]
authors = ["Magnus Hoff <maghoff@gmail.com>", "Johannes Hoff <johshoff@gmail.com>"]
name = "stach"
version = "0.1.0"

[dependencies]
nom = "2.0.1"
quick-error = "1.1.0"
stach_derive = { path = "libs/stach_derive" }
