[package]
authors = ["Magnus Hoff <maghoff@gmail.com>", "Johannes Hoff <johshoff@gmail.com>"]
name = "stach"
version = "0.1.0"

[dependencies]
stach_derive = { path = "libs/stach_derive" }

[features]
default = []
specialization = []
